Repository Walkover-Web-Solution/AI-middleware-frontend, pull requests merged in 2025-03, with the labels that each got.

#429 PROD deployment = testcase
  app/org/[org_id]/alerts/page.js
  app/org/[org_id]/bridges/configure/[id]/page.js
  app/org/[org_id]/bridges/testcase/[id]/page.js
  app/org/[org_id]/knowledge_base/page.js
  app/org/[org_id]/layout.js
  app/showcase/page.js
  components/ShowcaseCard.js
  components/ShowcaseSearch.js
  components/configuration/chat.js
  components/configuration/chatTextInput.js
  components/configuration/configurationComponent/functionParameterModal.js
  components/configuration/configurationComponent/inputConfigComponent.js
  components/historyPageComponents/chatDetails.js
  components/modals/publishBridgeVersionModal.js
  components/navbar.js
  components/withauth.js
  config/index.js
  customHooks/embedScriptLoader.js
  store/action/bridgeAction.js
  store/reducer/bridgeReducer.js
  utils/enums.js
Labels: PROD deployment

#443 model description
  components/configuration/configurationComponent/modelDropdown.js
Labels: feature

#437 bug fixes
  components/FeatureRequests.js
  components/Footer.js
  components/Questions.js
  components/SuggestionTemplate.js
  components/historyPageComponents/threadItem.js
  components/modals/ApiKeyModal.js
Labels: bug

#445 chatbot on history page main
  app/org/[org_id]/bridges/history/layout.js
  app/org/[org_id]/layout.js
  components/historyPageComponents/threadItem.js
  store/action/bridgeAction.js
  store/reducer/bridgeReducer.js
Labels: PROD deployment

#448 Testing to main
  app/org/[org_id]/bridges/configure/[id]/page.js
  app/org/[org_id]/bridges/history/[id]/page.js
  app/org/[org_id]/bridges/page.js
  app/org/[org_id]/bridges/testcase/[id]/page.js
  app/org/[org_id]/layout.js
  app/org/[org_id]/testcases/page.js
  components/FeatureRequests.js
  components/Footer.js
  components/Questions.js
  components/ShowcaseCard.js
  components/SuggestionTemplate.js
  components/addVariable.js
  components/configuration/chatTextInput.js
  components/configuration/chatbot.js
  components/configuration/configurationComponent/advancedParamenter.js
  components/configuration/configurationComponent/bridgeTypeToggle.js
  components/configuration/configurationComponent/inputConfigComponent.js
  components/configuration/configurationComponent/modelDropdown.js
  components/customTable/customTable.js
  components/historyPageComponents/sidebar.js
  components/historyPageComponents/threadContainer.js
  components/historyPageComponents/threadItem.js
  components/loadingSpinner.tsx
  components/modals/AddTestCaseModal.js
  components/modals/ApiKeyModal.js
  components/navbar.js
  components/sliders/mainSlider.js
Labels: PROD deployment

#450 hotfix version issue
  app/org/[org_id]/bridges/page.js
  app/org/[org_id]/bridges/testcase/[id]/page.js
  components/navbar.js
Labels: hotfix

#459 Minor changes
  components/ShowcaseCard.js
  components/addVariable.js
  components/configuration/ConfigurationPage.js
  components/configuration/configurationComponent/VersionDescriptionInput.js
  components/configuration/configurationComponent/bridgeNameInput.js
  components/configuration/configurationComponent/modelDropdown.js
  components/historyPageComponents/threadItem.js
Labels: PROD deployment

#465 History, Testcases, bug fixes
  app/org/[org_id]/bridges/history/[id]/page.js
  app/org/[org_id]/bridges/testcase/[id]/page.js
  app/org/[org_id]/layout.js
  app/page.js
  components/RoadMapCards.js
  components/historyPageComponents/sidebar.js
  components/historyPageComponents/threadContainer.js
  components/navbar.js
  config/index.js
  store/action/bridgeAction.js
  store/action/historyAction.js
  store/action/testCasesAction.js
  store/reducer/historyReducer.js
  store/reducer/testCasesReducer.js
Labels: PROD deployment

#467 PROD - Allow model switch
  components/chatbotConfiguration/formSection.js
Labels: PROD deployment

#471 chatbot variable issue on history page
  components/historyPageComponents/threadContainer.js
  components/historyPageComponents/threadItem.js
Labels: PROD deployment

#473 prod depllyment
  components/configuration/ConfigurationPage.js
  components/configuration/configurationComponent/actionList.js
  components/historyPageComponents/sidebar.js
Labels: PROD deployment

#469 Af00333/show button on hover of user message
  app/org/[org_id]/bridges/history/[id]/page.js
  components/historyPageComponents/chatDetails.js
  components/historyPageComponents/threadItem.js
Labels: feature

#480 Some fixes
  app/org/[org_id]/bridges/history/[id]/page.js
  components/historyPageComponents/chatDetails.js
  components/historyPageComponents/threadItem.js
Labels: PROD deployment

#481 added canonical
  app/page.js
  app/pricing/page.js
  app/privacy/page.js
  app/showcase/page.js
  app/terms/page.js
Labels: PROD deployment

#482 update webstie titlte acc to bridge name
  app/org/[org_id]/bridges/configure/[id]/page.js
  utils/utility.js
Labels: feature
