Repository Walkover-Web-Solution/AI-middleware-frontend, pull requests merged in 2025-04, with the labels that each got.

#483 remove data from function if function is deleted
  app/org/[org_id]/layout.js
  config/index.js
  store/action/bridgeAction.js
  store/reducer/bridgeReducer.js
Labels: good first issue

#484 serach memeber on invite page
  app/org/[org_id]/invite/page.js
Labels: enhancement

#485 add timezone in crete org modal
  components/createNewOrg.js
Labels: enhancement

#464 Af00226/user detials script
  app/org/[org_id]/userDetails/page.js
  components/sliders/mainSlider.js
Labels: feature

#489 first attempt error in history
  components/historyPageComponents/threadItem.js
Labels: improvement

#487 show message for api key if it is not in bridge
  app/org/[org_id]/bridges/configure/[id]/page.js
  components/BatchApi.js
  components/apiKeyMessage.js
  components/configuration/ConfigurationPage.js
  components/configuration/chat.js
  components/configuration/configurationComponent/apiKeyInput.js
  components/navbar.js
Labels: good first issue

#490 UI changes = prod
  app/org/[org_id]/bridges/configure/[id]/page.js
  app/org/[org_id]/invite/page.js
  app/org/[org_id]/layout.js
  app/org/[org_id]/metrics/page.js
  app/org/[org_id]/userDetails/page.js
  components/BatchApi.js
  components/apiKeyMessage.js
  components/configuration/ConfigurationPage.js
  components/configuration/chat.js
  components/configuration/configurationComponent/apiKeyInput.js
  components/createNewOrg.js
  components/historyPageComponents/threadItem.js
  components/navbar.js
  components/sliders/mainSlider.js
  config/index.js
  store/action/bridgeAction.js
  store/reducer/bridgeReducer.js
  utils/utility.js
Labels: PROD deployment

#486 render funtion and pre function only if the model supports
  components/configuration/configurationComponent/embedList.js
  components/configuration/configurationComponent/embedListSuggestionDropdownMenu.js
  components/configuration/configurationComponent/preEmbedList.js
Labels: improvement

#503 z index bugs
  app/globals.css
  components/apiKeyMessage.js
  components/configuration/configurationComponent/inputConfigComponent.js
  components/loadingSpinner.tsx
  components/navbar.js
  components/sliders/configHistorySlider.js
Labels: bug

#510 Af000346/response api testing
  app/org/[org_id]/layout.js
  components/configuration/ConfigurationPage.js
  components/configuration/configurationComponent/apiKeyInput.js
  components/configuration/configurationComponent/prebuiltToolsList.js
  config/index.js
  icons/webSearchIcon.tsx
  store/action/bridgeAction.js
  store/reducer/bridgeReducer.js
  utils/utility.js
Labels: feature

#508 History thread selection
  app/org/[org_id]/bridges/history/[id]/page.js
  components/historyPageComponents/sidebar.js
  components/historyPageComponents/threadContainer.js
  components/historyPageComponents/threadItem.js
  store/reducer/historyReducer.js
Labels: bug

#502 create new bridge on slash new
  app/new/page.js
  app/org/[org_id]/layout.js
  store/action/bridgeAction.js
Labels: good first issue

#454 best model suggestion
  components/configuration/configurationComponent/serviceDropdown.js
  config/index.js
Labels: feature

#511 Af000348/brigde on off feature
  components/configuration/chatTextInput.js
  components/navbar.js
  config/index.js
Labels: feature
